spin_manifest_version = 2

[application]
authors = ["Mossaka"]
description = "a command trigger"
name = "hello-command"
version = "0.1.0"

[[trigger.command]]
component = "hello-command"

[component.hello-command]
source = "target/wasm32-wasi/release/hello-command.wasm"
build = ["cargo component build --target wasm32-wasi --release"]